using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CCompiler
{
    public enum TokenTypes
    {
        EOF,
        ID,
        AOP_SUM,
        AOP_SUB,
        AOP_MUL,
        AOP_DIV,
        AOP_MOD,
        AOP_INCREMENT,
        AOP_DECREMENT,
        ROP_EQUAL,
        ROP_NOT_EQUAL,
        ROP_LESS_THAN,
        ROP_GREATER_THAN,
        ROP_GREATER_EQUAL,
        ROP_LESS_EQUAL,
        LOP_AND,
        LOP_OR,
        LOP_NOT,
        BOP_AND,
        BOP_OR,
        BOP_COMPLIMENT,
        BOP_XOR,
        BOP_LEFT_SHIFT,
        BOP_RIGHT_SHIFT,
        ASOP_EQUAL,
        ASOP_SUM,
        ASOP_SUB,
        ASOP_MUL,
        ASOP_DIV,
        ASOP_MOD,
        ASOP_LEFT_SHIFT,
        ASOP_RIGHT_SHIFT,
        ASOP_AND,
        ASOP_OR,
        ASOP_XOR,
        STRING_LITERAL,
        NUMBER_LITERAL,
        CHAR_LITERAL,
        KW_PRINT,
        KW_SCAN,
        TYPE_INT,
        TYPE_FLOAT,
        TYPE_CHAR,
        TYPE_BOOL,
        TYPE_STRING,
        TYPE_DATE,
        TYPE_ENUM,
        TYPE_STRUCT,
        KW_IF,
        KW_WHILE,
        KW_DO,
        KW_FOR,
        KW_SWITCH,
        KW_FOREACH,
        KW_BREAK,
        KW_CONTINUE,
        KW_VOID,
        TK_OPEN_PARENTHESIS,
        TK_CLOSE_PARENTHESIS,
        TK_OPEN_BRACE,
        TK_CLOSE_BRACE,
        TK_OPEN_BRACKET,
        TK_CLOSE_BRACKET,
        TK_COMMA,
        TK_PERIOD,
        TK_SEMICOLON,
        TK_STRUCTURE_DEREFERENCE,
        TK_HASHTAG,
        TK_INCLUDE
    }
}
